/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vyed0EMbldw
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu"


export function ConstructionBoard() {
  return (
    <main key="1" className="flex flex-col w-full min-h-screen p-4 md:p-8 bg-[rgb(34,34,34)] text-[rgb(255,255,255)]">
      <header className="flex items-center justify-between mb-4">
        <h1 className="text-2xl font-semibold text-[rgb(255,111,118)]">Construction Dashboard</h1>
        <Button className="bg-[rgb(128,128,128)] text-[rgb(255,255,255)]">Add New Construction</Button>
      </header>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        
        <a className="cursor-pointer" href="#">
          <Card className="bg-[rgb(0,0,0)]">
            <CardHeader className="flex flex-row items-center gap-4">
              <HomeIcon className="w-8 h-8 text-[rgb(128,128,128)]" />
              <div className="grid gap-1">
                <CardTitle className="text-[rgb(255,111,118)]">Construction 1</CardTitle>
                <CardDescription className="text-[rgb(235,235,235)]">123 Street, City</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">
                Current Stage:
                <Badge className="bg-[rgb(128,128,128)] text-[rgb(255,255,255)]">Foundation</Badge>
              </div>
              <div>
                Progress:
                <span className="font-bold text-[rgb(128,128,128)]">30%</span>
                <div className="h-2 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "30%",
                    }}
                  />
                </div>
              </div>
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">Budget: $500,000</div>
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">Expenditure: $150,000</div>
            </CardContent>
          </Card>
        </a>
        <a className="cursor-pointer" href="#">
          <Card className="bg-[rgb(0,0,0)]">
            <CardHeader className="flex flex-row items-center gap-4">
              <HomeIcon className="w-8 h-8 text-[rgb(128,128,128)]" />
              <div className="grid gap-1">
                <CardTitle className="text-[rgb(255,111,118)]">Construction 2</CardTitle>
                <CardDescription className="text-[rgb(235,235,235)]">456 Avenue, City</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">
                Current Stage:
                <Badge className="bg-[rgb(128,128,128)] text-[rgb(255,255,255)]">Plumbing</Badge>
              </div>
              <div>
                Progress:
                <span className="font-bold text-[rgb(128,128,128)]">60%</span>
                <div className="h-2 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "60%",
                    }}
                  />
                </div>
              </div>
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">Budget: $1,000,000</div>
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">Expenditure: $700,000</div>
            </CardContent>
          </Card>
        </a>
        <a className="cursor-pointer" href="#">
          <Card className="bg-[rgb(0,0,0)]">
            <CardHeader className="flex flex-row items-center gap-4">
              <HomeIcon className="w-8 h-8 text-[rgb(128,128,128)]" />
              <div className="grid gap-1">
                <CardTitle className="text-[rgb(255,111,118)]">Construction 3</CardTitle>
                <CardDescription className="text-[rgb(235,235,235)]">789 Boulevard, City</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">
                Current Stage:
                <Badge className="bg-[rgb(128,128,128)] text-[rgb(255,255,255)]">Roofing</Badge>
              </div>
              <div>
                Progress:
                <span className="font-bold text-[rgb(128,128,128)]">80%</span>
                <div className="h-2 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "80%",
                    }}
                  />
                </div>
              </div>
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">Budget: $750,000</div>
              <div className="text-sm font-semibold text-[rgb(128,128,128)]">Expenditure: $700,000</div>
            </CardContent>
          </Card>
        </a>
      </div>
      <section className="mt-8">
        <h2 className="text-2xl font-semibold text-[rgb(255,111,118)] mb-4 flex justify-between items-center">
          Task Manager
          <Button className="bg-[rgb(128,128,128)] text-[rgb(255,255,255)]">Add New Task</Button>
        </h2>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <Card className="bg-[rgb(0,0,0)]">
            <CardHeader>
              <CardTitle className="text-[rgb(255,111,118)]">To Do</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 1 - Assigned to John Doe</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "30%",
                    }}
                  />
                </div>
              </div>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 2 - Assigned to Jane Smith</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "60%",
                    }}
                  />
                </div>
              </div>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 3 - Assigned to Alex Johnson</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "20%",
                    }}
                  />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-[rgb(0,0,0)]">
            <CardHeader>
              <CardTitle className="text-[rgb(255,111,118)]">In Progress</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 4 - Assigned to Emily Brown</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "40%",
                    }}
                  />
                </div>
              </div>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 5 - Assigned to Michael Davis</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "70%",
                    }}
                  />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-[rgb(0,0,0)]">
            <CardHeader>
              <CardTitle className="text-[rgb(255,111,118)]">Done</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 6 - Assigned to Sarah Miller</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "100%",
                    }}
                  />
                </div>
              </div>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 7 - Assigned to Robert Wilson</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "100%",
                    }}
                  />
                </div>
              </div>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mb-2">
                <p className="cursor-move">Task 8 - Assigned to Jessica Taylor</p>
                <div className="h-1 w-full bg-[rgb(0,0,0)] mt-1">
                  <div
                    className="h-full bg-[rgb(128,128,128)]"
                    style={{
                      width: "100%",
                    }}
                  />
                </div>
              </div>
              <div className="bg-[rgb(34,34,34)] rounded-lg p-2 mt-4 cursor-move text-center text-[rgb(255,111,118)] border-2 border-dashed border-[rgb(255,111,118)]">
                Drag and Drop Here to File Tasks
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
    </main>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}
